export const RPW_SALES_TAX_COUNTIES = 'RPW_SALES_TAX_COUNTIES';
export const RPW_SALES_TAX_SETTINGS = 'RPW_SALES_TAX_SETTINGS';
export const RPW_SALES_TAX_COUNTY_SUMMARY = 'RPW_SALES_TAX_COUNTY_SUMMARY';

export const RpwSalesTaxQueryKeys = {
  RPW_SALES_TAX_COUNTIES,
  RPW_SALES_TAX_SETTINGS,
  RPW_SALES_TAX_COUNTY_SUMMARY,
} as const;
